name: artifacts
on: push
env:
  FILE_NAME: 'README.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check out the code
        uses: actions/checkout@v4
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ${{ env.FILE_NAME }}
