name: first
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step one
        uses: actions/checkout@v4
      - name: step two
        run: date
  job2:
    runs-on: windows-latest
    steps:
      - name: step one
        uses: actions/checkout@v4
      - name: step two
        run: date /t
  job3:
    runs-on: macos-latest
    steps:
      - name: step one
        uses: actions/checkout@v4
      - name: step two
        run: date
  job4:
    runs-on: ubuntu-latest
    needs: [job1, job2, job3]
    steps:
      - name: step one
        uses: actions/checkout@v4
      - name: step two
        run: date
